parameters:
    youshido.scopable.relation: workspace

services:
  scopable_subscriber:
      class: Youshido\DoctrineExtensionBundle\Scopable\ScopableSubscriber
      calls:
          - [ setAnnotationReader, [ @annotation_reader] ]
      tags:
          - { name: doctrine.event_subscriber }
      public: false

  aes_encrypt_subscriber:
      class: Youshido\DoctrineExtensionBundle\AesEncrypt\EncryptSubscriber
      calls:
          - [ setAnnotationReader, [ @annotation_reader] ]
      tags:
          - { name: doctrine.event_subscriber }
      public: false

  aes_encrypt_service:
    class: Youshido\DoctrineExtensionBundle\AesEncrypt\Service\EncryptService
    calls:
        - [ setContainer, [ @service_container ]]

  scopable_service:
    class: Youshido\DoctrineExtensionBundle\Scopable\Service\ScopableService
    calls:
        - [ setContainer, [ @service_container ] ]