parameters:
    youshido.scopable.relation: workspace

services:
  youshido_scope.scopable.scopable_subscriber:
      class: Youshido\DoctrineExtensionBundle\Scopable\ScopableSubscriber
      calls:
          - [ setAnnotationReader, [ @annotation_reader] ]
      tags:
          - { name: doctrine.event_subscriber }
      public: false

#  youshido_scope.encrypt.encrypt_subscriber:
#      class: Youshido\DoctrineExtensionBundle\Encrypt\EncryptSubscriber
#      calls:
#          - [ setAnnotationReader, [ @annotation_reader] ]
#      tags:
#          - { name: doctrine.event_subscriber }
#      public: false

  scopable_service:
    class: Youshido\DoctrineExtensionBundle\Scopable\Service\ScopableService
    calls:
        - [ setContainer, [ @service_container ] ]